import type { Category } from "./intent-engine";

export interface ServiceDropdownItem {
  id: string;
  title: string;
  category: Category;
  description: string;
  timeline: string;
  metrics: string;
  startingPrice?: string;
  badge?: string;
}

export interface ServiceDropdownGroup {
  id: string;
  columnNumber: string;
  name: string;
  tagline: string;
  items: ServiceDropdownItem[];
}

export const SERVICES_DROPDOWN_GROUPS: ServiceDropdownGroup[] = [
  {
    id: "web-design",
    columnNumber: "01",
    name: "Web Design",
    tagline: "High-converting, responsive websites & online shopping platforms",
    items: [
      {
        id: "static-website-design-services-in-india",
        title: "Static Website Design",
        category: "Website",
        description: "Fast, secure, and beautiful corporate websites providing instant brand authority with zero server bloat.",
        timeline: "1 - 2 Weeks",
        metrics: "Sub-0.8s Global Edge Load",
        startingPrice: "₹3,250",
      },
      {
        id: "dynamic-website-design-services-in-india",
        title: "Dynamic Website Design",
        category: "Website",
        description: "Content-rich websites powered by custom databases, blogging engines, and simple administrative control panels.",
        timeline: "2 - 3 Weeks",
        metrics: "Easy Admin Portal",
        startingPrice: "₹8,000",
      },
      {
        id: "ecommerce-website-design-services-in-india",
        title: "Ecommerce Website Design",
        category: "Website",
        description: "High-concurrency online stores built with instant UPI checkouts, inventory tracking, and GST automated invoicing.",
        timeline: "2 - 4 Weeks",
        metrics: "+180% More Sales",
        startingPrice: "₹15,999",
        badge: "Top Seller",
      },
      {
        id: "mobile-website-design-services-in-india",
        title: "Mobile Website Design",
        category: "Website",
        description: "Flawlessly responsive touch-first digital experiences tailored for smartphone users and tablet shoppers.",
        timeline: "1 - 2 Weeks",
        metrics: "100% Mobile Ready",
        startingPrice: "₹8,000",
      },
      {
        id: "red",
        title: "Redesign of Existing Website",
        category: "Website",
        description: "Re-engineer slow, outdated WordPress or template sites into lightning-fast Next.js conversion powerhouses.",
        timeline: "2 - 3 Weeks",
        metrics: "3.4x Speed & Lead Boost",
        startingPrice: "₹9,999",
      },
    ],
  },
  {
    id: "digital-marketing",
    columnNumber: "02",
    name: "Digital Marketing",
    tagline: "360° targeted growth campaigns & SEO that attract ready buyers",
    items: [
      {
        id: "search-engine-optimization-seo-outsourcing-to-india",
        title: "Search Engine Optimisation",
        category: "Digital Marketing",
        description: "Rank #1 on Google for high-intent search terms so ready-to-buy local and global customers discover you first.",
        timeline: "Ongoing Retainer",
        metrics: "Top 3 Google Ranking",
        startingPrice: "₹9,999/mo",
        badge: "High ROI",
      },
      {
        id: "social-media-marketing-services",
        title: "Social Media Marketing",
        category: "Digital Marketing",
        description: "Engaging social content, daily post design, community building, and ad management across Instagram, Facebook & LinkedIn.",
        timeline: "Monthly Retainer",
        metrics: "3.8x ROI & Reach",
        startingPrice: "₹3,000/mo",
      },
      {
        id: "bulk-sms-marketing-services-in-india",
        title: "Bulk SMS Broadcasting & Marketing",
        category: "Digital Marketing",
        description: "Direct transactional SMS, OTP alerts, and promotional broadcasts delivered instantaneously straight to mobile handsets.",
        timeline: "Instant Setup",
        metrics: "98% Open Rate",
        startingPrice: "₹3,000",
      },
      {
        id: "whatsapp-marketing-services-in-inida",
        title: "Whatsapp Messaging",
        category: "AI Automation",
        description: "Official WhatsApp Business API integration, broadcast updates, catalog messaging, and automated responder bots.",
        timeline: "1 - 2 Days",
        metrics: "Direct 24/7 Engagement",
        startingPrice: "₹3,000",
        badge: "High Conversion",
      },
      {
        id: "ads",
        title: "Google Adwords (PPC)",
        category: "Digital Marketing",
        description: "Laser-targeted pay-per-click Google search, display, and shopping ad campaigns engineered for immediate lead generation.",
        timeline: "3 Days Setup",
        metrics: "Immediate Inquiries",
        startingPrice: "₹4,999",
      },
      {
        id: "review-services-in-india",
        title: "Reviews & Reputation Management",
        category: "Digital Marketing",
        description: "Build authentic Google Business 5-star reputation, collect customer testimonials, and manage brand trust online.",
        timeline: "Ongoing",
        metrics: "5-Star Trust Score",
        startingPrice: "₹2,499",
      },
    ],
  },
  {
    id: "mobile-apps",
    columnNumber: "03",
    name: "Mobile Apps",
    tagline: "Native iOS & Android applications for customers and operations",
    items: [
      {
        id: "ecommerce-mobile-app-development-services-in-india",
        title: "Ecommerce Mobile App Development",
        category: "App",
        description: "Native iOS & Android shopping applications with push notifications, UPI payment gateway, and order tracking.",
        timeline: "4 - 6 Weeks",
        metrics: "99.9% Crash-Free",
        startingPrice: "₹43,000",
        badge: "Top Rated",
      },
      {
        id: "ecommerce-multivendor-mobile-app-development-services-in-india",
        title: "Multivendor Mobile App Development",
        category: "App",
        description: "Complete marketplace app suite connecting vendors, buyers, and delivery drivers with real-time tracking.",
        timeline: "2 - 3 Months",
        metrics: "Scalable Marketplace",
        startingPrice: "₹58,000",
      },
      {
        id: "video-streaming-ott-app-development-services-in-india",
        title: "Video Streaming App (OTT) Development",
        category: "App",
        description: "High-concurrency video streaming apps with DRM content security, subscription tiers, and buffer-free mobile playback.",
        timeline: "2 - 3 Months",
        metrics: "Buffer-Free HD/4K",
        startingPrice: "₹95,000",
      },
      {
        id: "online-food-delivery-mobile-app-development-service-in-india",
        title: "Food Ordering Mobile App Development",
        category: "App",
        description: "Restaurant and food delivery app with live GPS delivery driver tracking, menu customizations, and instant UPI checkout.",
        timeline: "3 - 5 Weeks",
        metrics: "Direct Orders & No Fee",
        startingPrice: "₹48,000",
      },
      {
        id: "online-consultation-mobile-app",
        title: "Consultation & Telehealth App",
        category: "App",
        description: "Video consultation mobile app for doctors, lawyers, and experts with slot scheduling and online fee collection.",
        timeline: "4 - 6 Weeks",
        metrics: "HD Video & Slot Booking",
        startingPrice: "₹38,000",
      },
      {
        id: "marketplace-mobile-app-development",
        title: "Marketplace & Services App",
        category: "App",
        description: "On-demand booking app connecting users with local service providers, home technicians, or professional rentals.",
        timeline: "6 - 8 Weeks",
        metrics: "On-Demand Booking",
        startingPrice: "₹52,000",
      },
    ],
  },
  {
    id: "web-portals",
    columnNumber: "04",
    name: "Web Portals",
    tagline: "Specialized enterprise web platforms, LMS & community portals",
    items: [
      {
        id: "online-learning-portal-development-service-in-india",
        title: "Online Learning Web Portal (LMS)",
        category: "Website",
        description: "Interactive learning management systems with video streaming, student quizzes, automated certificate generation, and fee portals.",
        timeline: "4 - 6 Weeks",
        metrics: "Full LMS Platform",
        startingPrice: "₹43,000",
        badge: "EdTech",
      },
      {
        id: "online-matrimony-website-development-service-in-india",
        title: "Matrimony Web Portal",
        category: "Website",
        description: "High-security matchmaking platforms with advanced profile search, verification badges, privacy settings, and subscription plans.",
        timeline: "6 - 8 Weeks",
        metrics: "Verified Profiles Engine",
        startingPrice: "₹71,000",
      },
      {
        id: "online-food-delivery-web-portal-development-service-in-india",
        title: "Food Delivery Web Portal",
        category: "Website",
        description: "Web ordering platform for restaurants and cloud kitchens featuring live order tracking, kitchen dispatching, and zero commissions.",
        timeline: "3 - 5 Weeks",
        metrics: "Real-Time Dispatching",
        startingPrice: "₹68,000",
      },
      {
        id: "online-news-portal-development-service-in-india",
        title: "Online News Portal Development",
        category: "Website",
        description: "High-traffic digital journalism portals with ad integration, breaking news ticker, RSS feeds, and instant news publishing.",
        timeline: "3 - 4 Weeks",
        metrics: "High-Traffic Ready",
        startingPrice: "₹10,000",
      },
      {
        id: "Free-Classifieds-Portal",
        title: "Free Classifieds Portal",
        category: "Website",
        description: "Geo-targeted buyer and seller marketplace portals with listing management, user chat, and sponsored ad placements.",
        timeline: "4 - 6 Weeks",
        metrics: "Community Directory",
        startingPrice: "₹35,000",
      },
      {
        id: "Forum",
        title: "Discussion Forum & Portal",
        category: "Website",
        description: "Community discussion platforms with thread moderation, member rep scores, private messaging, and user roles.",
        timeline: "3 - 4 Weeks",
        metrics: "High Member Engagement",
        startingPrice: "₹25,000",
      },
      {
        id: "Blogs",
        title: "Blogging & Content Portal",
        category: "Website",
        description: "SEO-optimized publishing portals designed for content creators, magazine hubs, and corporate thought leadership.",
        timeline: "2 - 3 Weeks",
        metrics: "SEO Article Engine",
        startingPrice: "₹12,000",
      },
      {
        id: "game-result-display-web-development",
        title: "Game & Result Display Portal",
        category: "Website",
        description: "Real-time sports and contest score tracking portals with instant WebSocket updates and high-concurrency architecture.",
        timeline: "3 - 5 Weeks",
        metrics: "Live Realtime Scores",
        startingPrice: "₹45,000",
      },
    ],
  },
  {
    id: "softwares",
    columnNumber: "05",
    name: "Softwares",
    tagline: "Custom enterprise software, ERP platforms & automated billing",
    items: [
      {
        id: "school-management-online-software-in-india",
        title: "School Management Software",
        category: "Custom Software",
        description: "All-in-one school ERP managing student admissions, fee collection, attendance, exam marksheets, and parent SMS updates.",
        timeline: "4 - 6 Weeks",
        metrics: "Saves 30+ Hours/Week",
        startingPrice: "₹3,000/mo",
        badge: "Essential",
      },
      {
        id: "college-management-online-software-in-india",
        title: "College Management Software",
        category: "Custom Software",
        description: "Comprehensive university campus ERP automating department workflows, hostel allocations, admissions, and library logs.",
        timeline: "2 - 3 Months",
        metrics: "Unified Campus ERP",
        startingPrice: "₹440,000",
      },
      {
        id: "vocational-school-management-online-software-in-india",
        title: "Vocational Institute Management",
        category: "Custom Software",
        description: "Training center software for batch scheduling, student skill tracking, corporate placement automation, and fee reminders.",
        timeline: "4 - 6 Weeks",
        metrics: "Streamlined Batches",
        startingPrice: "₹125,000",
      },
      {
        id: "billing-accounting-software-in-india",
        title: "Billing & Client Management (CRM)",
        category: "Custom Software",
        description: "Replace paperwork with automated GST invoicing, client ledger tracking, quotation generation, and payment reminders.",
        timeline: "2 - 4 Weeks",
        metrics: "Automated GST & CRM",
        startingPrice: "₹15,000",
      },
      {
        id: "Restaurant-Management",
        title: "Restaurant Management System",
        category: "Custom Software",
        description: "Point of sale (POS) billing system with Kitchen Order Tickets (KOT), table management, and inventory ingredient alerts.",
        timeline: "3 - 4 Weeks",
        metrics: "Table to Kitchen POS",
        startingPrice: "₹25,000",
      },
      {
        id: "POS-and-Billing",
        title: "Retail POS and Billing Software",
        category: "Custom Software",
        description: "Fast barcode retail billing software with thermal receipt printing, stock inventory tracking, and daily sales reports.",
        timeline: "2 - 3 Weeks",
        metrics: "Fast Counter Checkout",
        startingPrice: "₹18,000",
      },
      {
        id: "pharmaceutical-drug-distributor-reporting-system",
        title: "Pharmaceutical Reporting System",
        category: "Custom Software",
        description: "Drug distributor sales tracking software managing batch expiration dates, medical rep reporting, and GST compliance.",
        timeline: "4 - 6 Weeks",
        metrics: "Compliant Drug Tracking",
        startingPrice: "₹48,000",
      },
    ],
  },
  {
    id: "graphic-design",
    columnNumber: "06",
    name: "Graphic Design",
    tagline: "Distinctive brand identity & high-impact marketing collateral",
    items: [
      {
        id: "logo-design-services-in-india",
        title: "Logo Design",
        category: "Website",
        description: "Memorable corporate logo design, brand identity systems, typography, and vector master assets.",
        timeline: "3 - 5 Days",
        metrics: "Distinctive Brand ID",
        startingPrice: "₹1,999",
        badge: "Popular",
      },
      {
        id: "flyer-design-services-in-india",
        title: "Flyer Design",
        category: "Digital Marketing",
        description: "High-converting single & multi-page promotional flyers designed for digital campaigns and offline distribution.",
        timeline: "2 - 3 Days",
        metrics: "High Campaign Engagement",
        startingPrice: "₹999",
      },
      {
        id: "brochure-design-services-in-india",
        title: "Brochure Design",
        category: "Digital Marketing",
        description: "Professional corporate brochures, bi-folds, tri-folds, and sales pitch decks built to leave a lasting impression.",
        timeline: "3 - 5 Days",
        metrics: "Executive Presentation",
        startingPrice: "₹999",
      },
      {
        id: "poster-design-services-in-india",
        title: "Poster Design",
        category: "Digital Marketing",
        description: "Vibrant event posters, social media banners, and outdoor advertising visuals optimized for maximum attention.",
        timeline: "2 - 3 Days",
        metrics: "High Click & Event Reach",
        startingPrice: "₹999",
      },
      {
        id: "catalogue-design",
        title: "Catalogue Design",
        category: "Website",
        description: "Comprehensive product catalogues displaying inventory with high-resolution layouts and clear technical specs.",
        timeline: "4 - 6 Days",
        metrics: "Complete Product Showcase",
        startingPrice: "₹1,999",
      },
      {
        id: "menu-design",
        title: "Menu Design",
        category: "Website",
        description: "Custom restaurant, cafe, and hotel menu cards with appetising typography, QR-code integration, and print files.",
        timeline: "2 - 3 Days",
        metrics: "Appetising Layout",
        startingPrice: "₹1,499",
      },
      {
        id: "postcard-design",
        title: "Postcard Design",
        category: "Digital Marketing",
        description: "Direct-mail postcards, invitation cards, and promotional mailers built for targeted client outreach.",
        timeline: "2 - 3 Days",
        metrics: "High Direct Response",
        startingPrice: "₹899",
      },
      {
        id: "invitation-design",
        title: "Invitation Design",
        category: "Digital Marketing",
        description: "Elegant corporate launch invitations, event passes, and digital e-invites with custom typography.",
        timeline: "2 - 3 Days",
        metrics: "Elegant Guest Experience",
        startingPrice: "₹999",
      },
    ],
  },
];
